# Generated by Django 5.1.3 on 2024-11-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'T-Shirt'), ('Men', 'Sports-T-Shirt'), ('Women', 'T-Shirt'), ('Women', 'Sports-T-Shirt'), ('Kids', 'T-Shirt'), ('Kids', 'Sports-T-Shirt')], max_length=5),
        ),
    ]
