# Generated by Django 5.1.3 on 2024-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_product_gender_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-S', 'T-Shirt'), ('S-T-S', 'Sports-T-Shirt'), ('C-T-S', 'Casual-T-Shirt')], max_length=20),
        ),
    ]
