# Generated by Django 5.1.3 on 2024-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M-T-S', 'T-Shirt'), ('M-S-T-S', 'Sports-T-Shirt'), ('M-C-T-S', 'Casual-T-Shirt'), ('W-T-S', 'T-Shirt'), ('W-S-T-S', 'Sports-T-Shirt'), ('W-C-T-S', 'Casual-T-Shirt'), ('K-T-S', 'T-Shirt'), ('K-S-T-S', 'Sports-T-Shirt'), ('K-C-T-S', 'Casual-T-Shirt')], max_length=20),
        ),
    ]
